// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  schemaSideBar: [{type: 'autogenerated', dirName: "schema"}],
  RESTAPISideBar: [{type: 'autogenerated', dirName: "restapi"}],
  AuthAPISidebar: [{type: 'autogenerated', dirName: "authapi"}],
  xmlSidebar: [{type: 'autogenerated', dirName: "ixml"}],
  zymbaSidebar: [{type: 'autogenerated', dirName: "zymba"}],
  sdkSideBar: [{type: 'autogenerated', dirName: "sdk"}]
};

export default sidebars;
