// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // ... other sidebars config
  xmlSidebar: [
    {
      type: 'category',
      label: 'iXML Documentation',
      link: {
        type: 'doc',
        id: 'ixml-intro', // The doc ID of your introduction page
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'ixml', // The directory name where your iXML docs are located
        },
      ],
      collapsible:false
    },
    // ... rest of your sidebar configuration
  ],
  // ... rest of your sidebar configuration
};

export default sidebars;
